export const data = [
    {
      id: 1,
      problem_no: 1,
      title: "Two Sum",
      desc: 'Given an array of integers, find two numbers such that they add up to a specific target.',
      input: { nums: [2, 7, 11, 15], target: 9 },
      output: [0, 1],
    },
    {
      id: 2,
      problem_no: 2,
      title: "Reverse a String",
      desc: 'Write a function that reverses a string. Do it in-place.',
      input: { s: "hello" },
      output: "olleh",
    },
    {
      id: 3,
      problem_no: 3,
      title: "Merge Intervals",
      desc: 'Given a collection of intervals, merge overlapping intervals.',
      input: { intervals: [[1,3],[2,6],[8,10],[15,18]] },
      output: [[1,6],[8,10],[15,18]],
    },
    {
      id: 4,
      problem_no: 4,
      title: "Binary Tree Inorder Traversal",
      desc: 'Given the root of a binary tree, return the inorder traversal of its nodes\' values.',
      input: { root: [1, null, 2, 3] },
      output: [1, 3, 2],
    },
    {
      id: 5,
      problem_no: 5,
      title: "Longest Palindromic Substring",
      desc: 'Given a string, find the longest palindromic substring.',
      input: { s: "babad" },
      output: "bab" // or "aba"
    },
    {
      id: 6,
      problem_no: 6,
      title: "Maximum Subarray",
      desc: 'Find the contiguous subarray with the largest sum and return its sum.',
      input: { nums: [-2,1,-3,4,-1,2,1,-5,4] },
      output: 6,
    },
    {
      id: 7,
      problem_no: 7,
      title: "Valid Parentheses",
      desc: 'Given a string containing just the characters \'(\', \')\', \'{\', \'}\', \'[\' and \']\', determine if the input string is valid.',
      input: { s: "{[]}" },
      output: true,
    },
    {
      id: 8,
      problem_no: 8,
      title: "Container With Most Water",
      desc: 'Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.',
      input: { height: [1,8,6,2,5,4,8,3,7] },
      output: 49,
    },
    {
      id: 9,
      problem_no: 9,
      title: "Subarray Sum Equals K",
      desc: 'Given an array of integers nums and an integer k, return the total number of continuous subarrays whose sum equals to k.',
      input: { nums: [1,1,1], k: 2 },
      output: 2,
    },
    {
      id: 10,
      problem_no: 10,
      title: "Top K Frequent Elements",
      desc: 'Given an integer array nums and an integer k, return the k most frequent elements.',
      input: { nums: [1,1,1,2,2,3], k: 2 },
      output: [1,2],
    },
  ];
  